module.exports = {
  apps: [
    {
      name: "lp-data",
      script: "npx",
      args: "tsx packages/data-service/src/index.ts",
      cwd: "/Users/lewisjackson/defi-lp-engine",
      env: { NODE_ENV: "production", PORT: 4001 },
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
    },
    {
      name: "lp-ml",
      script: "npx",
      args: "tsx packages/ml-inference/src/index.ts",
      cwd: "/Users/lewisjackson/defi-lp-engine",
      env: { NODE_ENV: "production", PORT: 4002 },
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
    },
    {
      name: "lp-execution",
      script: "npx",
      args: "tsx packages/execution-engine/src/index.ts",
      cwd: "/Users/lewisjackson/defi-lp-engine",
      env: { NODE_ENV: "production", PORT: 4003, PORT_EXECUTION: 4003 },
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
    },
    {
      name: "lp-risk",
      script: "npx",
      args: "tsx packages/risk-service/src/index.ts",
      cwd: "/Users/lewisjackson/defi-lp-engine",
      env: { NODE_ENV: "production", PORT: 4004 },
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
    },
    {
      name: "lp-dashboard",
      script: "npx",
      args: "tsx packages/dashboard/server/index.ts",
      cwd: "/Users/lewisjackson/defi-lp-engine",
      env: { NODE_ENV: "production", PORT: 4000 },
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
    },
  ],
};
